### PR TITLE
Fix for gpsd-3.19 compatibility

### PR DESCRIPTION
**Pull request by lukehutch**
Fix for https://github.com/swri-robotics/gps_umd/issues/25 , based on the documented changes in `/usr/include/gps.h`

### CODE REVIEW

**Comment by lukehutch** [comment]
Oops, I made one more change to this PR, and should have done it on a separate feature branch, but it ended up in this PR. It seems to be the right patch though to fix an issue with duplicated fix messages, based on the patch suggested here:

https://github.com/ros-drivers/gps_umd/issues/3

See also 

https://github.com/swri-robotics/gps_umd/issues/14

**Comment by pjreed** [comment]
It looks like `/usr/include/gps.h` has a `GPSD_API_MAJOR_VERSION` version number that you could use to put some `#ifdef`s around this to make it compatible with different versions.

**Comment by lukehutch** [comment]
@pjreed Sorry, I should have done that before. Fixed.

**Comment by pjreed** [comment]
Thanks, that looks good!

**Pull request merged**
